export interface SOSStateData {
  slug: string;
  name: string;
  abbreviation: string;
  sosPortalUrl: string;
  sosPortalName: string;
  entityTypes: string[];
  onlineAvailability: string;
  dataAvailable: string[];
  steps: string[];
  gotchas: string[];
  processingTime: string;
}

export const SOS_STATES: SOSStateData[] = [
  {
    slug: "california",
    name: "California",
    abbreviation: "CA",
    sosPortalUrl: "https://bizfileonline.sos.ca.gov/search/business",
    sosPortalName: "bizfile Online",
    entityTypes: ["LLC", "Corporation", "LP", "LLP", "General Partnership"],
    onlineAvailability: "Free, real-time results",
    dataAvailable: ["Entity name", "Entity number", "Formation date", "Status", "Registered agent", "Filing history", "Statements of Information"],
    steps: [
      "Go to bizfile Online (bizfileonline.sos.ca.gov/search/business).",
      "Enter the entity name in the search field. Use the exact legal name for best results.",
      "Select the entity type filter if you know it (LLC, Corp, etc.), or leave as 'All'.",
      "Click Search. Results appear immediately.",
      "Click the entity number to view the full detail page with formation date, agent, and filing history.",
      "Check the Status field — 'Active' means in good standing. 'Suspended' or 'Dissolved' are red flags.",
      "Review the Statement of Information for current officer/member names and addresses.",
    ],
    gotchas: [
      "California has two filing systems — business entities (SOS) and fictitious business names (county). The SOS only covers formal entity registrations.",
      "LLCs must file a Statement of Information within 90 days of formation and biennially thereafter. A missing or overdue SOI doesn't mean the entity is suspended, but it's a compliance concern.",
      "California suspends entities aggressively for unpaid Franchise Tax Board (FTB) minimum tax ($800/year). A suspended entity cannot transact business or hold title.",
      "'Cancelled' status in California is equivalent to 'dissolved' — the entity no longer exists.",
    ],
    processingTime: "Real-time",
  },
  {
    slug: "florida",
    name: "Florida",
    abbreviation: "FL",
    sosPortalUrl: "https://search.sunbiz.org/Inquiry/CorporationSearch/ByName",
    sosPortalName: "Sunbiz",
    entityTypes: ["LLC", "Corporation", "LP", "LLP", "Foreign entities"],
    onlineAvailability: "Free, real-time results",
    dataAvailable: ["Entity name", "Document number", "Filing date", "Status", "Registered agent", "Annual reports", "Principal address", "Officer/Member names"],
    steps: [
      "Go to Sunbiz (search.sunbiz.org).",
      "Select 'Search by Entity Name' and enter the business name.",
      "Click Search. Results load immediately.",
      "Click the entity name to view the detail record.",
      "Check the Status field — 'Active' is good. 'Inactive' means the entity has been dissolved or revoked.",
      "Review Annual Reports section — Florida requires annual reports by May 1. Missed reports lead to administrative dissolution.",
      "Check the Registered Agent section for current agent name and address.",
    ],
    gotchas: [
      "Florida dissolves LLCs automatically if the annual report is not filed by the third Friday after September 1. Reinstatement is possible but not automatic.",
      "Sunbiz shows both domestic and foreign entities. A foreign entity registered in Florida may be formed in another state — verify in both states.",
      "Florida does not require LLCs to list members publicly. Only 'authorized person' or 'manager' names appear in filings.",
      "The 'FEI/EIN Number' field in Sunbiz is the federal tax ID — useful for cross-referencing.",
    ],
    processingTime: "Real-time",
  },
  {
    slug: "texas",
    name: "Texas",
    abbreviation: "TX",
    sosPortalUrl: "https://mycpa.cpa.state.tx.us/coa/",
    sosPortalName: "Texas Comptroller / SOSDirect",
    entityTypes: ["LLC", "Corporation", "LP", "LLP", "Professional entities"],
    onlineAvailability: "Free, but can be slow (30s-2min for some queries)",
    dataAvailable: ["Entity name", "Filing number", "Formation date", "Status", "Registered agent", "Franchise tax status"],
    steps: [
      "For tax/good standing status: go to the Texas Comptroller (mycpa.cpa.state.tx.us/coa/) and search by entity name.",
      "For formation details: go to SOSDirect (direct.sos.state.tx.us/corp/acct/ssearch.asp) for the SOS filing records.",
      "Enter the entity name. Texas search is partial-match, so abbreviations may work.",
      "Review the Taxpayer Status — 'Active' means franchise tax is current. 'Not Active' is a red flag.",
      "On SOSDirect, click 'Filing History' to see all amendments, mergers, and agent changes.",
      "Check both systems — an entity can be active with the SOS but delinquent with the Comptroller.",
    ],
    gotchas: [
      "Texas has TWO separate systems: the Secretary of State (entity formation) and the Comptroller (franchise tax/good standing). Both must be checked.",
      "SOSDirect searches can take 30 seconds to 2 minutes for some queries. Cobalt Intelligence handles this with long-polling.",
      "Texas forfeits entities for failure to file franchise tax. Forfeiture means the entity loses its right to transact business.",
      "'Involuntary termination' means the SOS has terminated the entity, which is more severe than a tax forfeiture.",
    ],
    processingTime: "30 seconds to 2 minutes (SOSDirect)",
  },
  {
    slug: "new-york",
    name: "New York",
    abbreviation: "NY",
    sosPortalUrl: "https://appext20.dos.ny.gov/corp_public/CORPSEARCH.ENTITY_SEARCH_ENTRY",
    sosPortalName: "Division of Corporations",
    entityTypes: ["LLC", "Corporation", "LP", "LLP"],
    onlineAvailability: "Free, real-time results",
    dataAvailable: ["Entity name", "DOS ID", "Formation date", "Status", "County", "Process address"],
    steps: [
      "Go to the NY Division of Corporations entity search portal.",
      "Enter the entity name and select 'Contains' or 'Begins with' for the search type.",
      "Click Search. Results appear immediately.",
      "Click the entity name to view details.",
      "Note: New York shows limited information online. Formation date, jurisdiction, status, and process address are available.",
      "For registered agent details or full filing history, you may need to order certified copies (fee-based).",
    ],
    gotchas: [
      "New York's online database shows less information than most states. You won't see officer names, member names, or annual filing status online.",
      "New York requires LLCs to publish articles of organization in two newspapers within 120 days of formation. Non-compliance can result in suspension.",
      "The 'Process Address' is where legal papers are served — it may differ from the registered agent in other states.",
      "NY charges $9 per entity for certified status letters. The online search only confirms basic existence.",
    ],
    processingTime: "Real-time",
  },
  {
    slug: "arizona",
    name: "Arizona",
    abbreviation: "AZ",
    sosPortalUrl: "https://ecorp.azcc.gov/EntitySearch/Index",
    sosPortalName: "Arizona Corporation Commission (eCorp)",
    entityTypes: ["LLC", "Corporation", "LP", "LLP", "Benefit Corporation"],
    onlineAvailability: "Free, real-time results",
    dataAvailable: ["Entity name", "File number", "Formation date", "Status", "Registered agent", "Annual reports", "Officer/Member names"],
    steps: [
      "Go to the Arizona Corporation Commission eCorp portal.",
      "Enter the entity name and click Search.",
      "Click the entity name in results to view the detail page.",
      "Check Status — 'Active/In Good Standing' is what you want. 'Revoked' or 'Admin Dissolved' are problems.",
      "Review the Annual Report section for filing compliance.",
      "Check the Registered Agent tab for current agent information.",
    ],
    gotchas: [
      "Arizona's entity search is managed by the Corporation Commission, not the Secretary of State (Arizona doesn't have an SOS for business filings).",
      "LLCs in Arizona file annual reports. Failure to file for 2+ years leads to administrative dissolution.",
      "Arizona distinguishes between 'Inactive' (voluntary dissolution) and 'Revoked' (administrative action).",
    ],
    processingTime: "Real-time",
  },
  {
    slug: "nevada",
    name: "Nevada",
    abbreviation: "NV",
    sosPortalUrl: "https://esos.nv.gov/EntitySearch/OnlineEntitySearch",
    sosPortalName: "SilverFlume / NVSOS",
    entityTypes: ["LLC", "Corporation", "LP", "Statutory Trust"],
    onlineAvailability: "Free, real-time results",
    dataAvailable: ["Entity name", "NV Business ID", "Formation date", "Status", "Registered agent", "Officers/Managers", "Annual list filings"],
    steps: [
      "Go to the Nevada SOS entity search (SilverFlume).",
      "Enter the entity name and click Search.",
      "Click the entity name in results.",
      "Check Status — 'Active' is good. 'Revoked', 'Default', or 'Permanently Revoked' indicate problems.",
      "Review the Annual List section — Nevada requires annual list filings with officer/manager details.",
      "Check for any 'Revenue Default' status which means the entity owes state business license fees.",
    ],
    gotchas: [
      "Nevada is a popular incorporation state due to privacy and tax benefits. Many entities are formed in NV but operate elsewhere — verify the property state registration too.",
      "Nevada 'Permanently Revoked' status cannot be reinstated. The entity is dead.",
      "'Revenue Default' means the entity hasn't paid its annual state business license fee. It can still transact but is not in good standing.",
      "Nevada requires relatively little public disclosure — member/manager names appear on annual lists but beneficial ownership is limited.",
    ],
    processingTime: "Real-time",
  },
  {
    slug: "colorado",
    name: "Colorado",
    abbreviation: "CO",
    sosPortalUrl: "https://www.sos.state.co.us/biz/BusinessEntityCriteriaExt.do",
    sosPortalName: "Colorado Secretary of State",
    entityTypes: ["LLC", "Corporation", "LP", "LLP", "Cooperative"],
    onlineAvailability: "Free, real-time results",
    dataAvailable: ["Entity name", "Entity ID", "Formation date", "Status", "Registered agent", "Periodic reports", "Principal address"],
    steps: [
      "Go to the Colorado SOS business search portal.",
      "Enter the entity name and click Search.",
      "Click the entity ID in results to view details.",
      "Check Status — 'Good Standing' is the target. 'Delinquent' means periodic reports are overdue.",
      "Review Periodic Reports — Colorado requires annual or biennial reports depending on entity type.",
      "The 'Principal Office Address' and registered agent are both visible.",
    ],
    gotchas: [
      "Colorado uses the term 'Periodic Report' instead of 'Annual Report'. LLCs file every other year; corporations file annually.",
      "'Delinquent' status means reports are overdue but the entity still exists. After 2+ years delinquent, the state may dissolve it.",
      "Colorado shows good information online including agent name, principal address, and all periodic report filings.",
    ],
    processingTime: "Real-time",
  },
  {
    slug: "georgia",
    name: "Georgia",
    abbreviation: "GA",
    sosPortalUrl: "https://ecorp.sos.ga.gov/BusinessSearch",
    sosPortalName: "Georgia Corporations Division",
    entityTypes: ["LLC", "Corporation", "LP", "LLP"],
    onlineAvailability: "Free, real-time results",
    dataAvailable: ["Entity name", "Control number", "Formation date", "Status", "Registered agent", "Annual registrations", "Principal office"],
    steps: [
      "Go to the Georgia Secretary of State Corporations Division search.",
      "Enter the entity name and select search type.",
      "Click the entity in results to view details.",
      "Check Status — 'Active/Compliance' is good standing.",
      "Review Annual Registration filings — Georgia requires annual registration for all entities.",
      "Verify registered agent and principal office address.",
    ],
    gotchas: [
      "Georgia administratively dissolves entities that miss annual registrations for 2 years.",
      "Georgia uses 'Control Number' as the unique entity identifier.",
      "The annual registration is essentially a confirmation that the entity's information is current — it's cheap ($50 for LLCs) but failure to file has consequences.",
    ],
    processingTime: "Real-time",
  },
  {
    slug: "north-carolina",
    name: "North Carolina",
    abbreviation: "NC",
    sosPortalUrl: "https://www.sosnc.gov/online_services/search/by_title/_Business_Registration",
    sosPortalName: "NC Secretary of State",
    entityTypes: ["LLC", "Corporation", "LP", "LLP"],
    onlineAvailability: "Free, real-time results",
    dataAvailable: ["Entity name", "SOS ID", "Formation date", "Status", "Registered agent", "Annual reports"],
    steps: [
      "Go to the NC Secretary of State business registration search.",
      "Enter the entity name and click Search.",
      "Click the entity name to view the full record.",
      "Check Status — 'Current-Active' is good standing.",
      "Review annual report filings for compliance.",
      "Verify registered agent details.",
    ],
    gotchas: [
      "North Carolina requires annual reports filed by April 15 each year.",
      "'Suspended' status means the entity has been administratively suspended for non-compliance but may be reinstated.",
      "NC distinguishes between 'Current-Active' and 'Admin Dissolved' — the latter requires reinstatement filing and fees.",
    ],
    processingTime: "Real-time",
  },
  {
    slug: "tennessee",
    name: "Tennessee",
    abbreviation: "TN",
    sosPortalUrl: "https://tnbear.tn.gov/ECommerce/FilingSearch.aspx",
    sosPortalName: "TNBEAR (Tennessee Business Entity and Registrations)",
    entityTypes: ["LLC", "Corporation", "LP", "LLP", "General Partnership"],
    onlineAvailability: "Free, real-time results",
    dataAvailable: ["Entity name", "Control number", "Formation date", "Status", "Registered agent", "Annual reports", "Principal office"],
    steps: [
      "Go to TNBEAR (tnbear.tn.gov).",
      "Enter the entity name in the search field.",
      "Click Search. Results appear immediately.",
      "Click the entity name to view details.",
      "Check Status — 'Active' is good. 'Inactive' or 'Dissolved' indicate issues.",
      "Review annual report filings for compliance.",
    ],
    gotchas: [
      "Tennessee uses the name 'TNBEAR' for their business entity system.",
      "Annual reports in Tennessee are due by the first day of the fourth month after the fiscal year end.",
      "Tennessee is generally straightforward — the online portal shows comprehensive information.",
    ],
    processingTime: "Real-time",
  },
  {
    slug: "ohio",
    name: "Ohio",
    abbreviation: "OH",
    sosPortalUrl: "https://businesssearch.ohiosos.gov/",
    sosPortalName: "Ohio Secretary of State Business Search",
    entityTypes: ["LLC", "Corporation", "LP", "LLP"],
    onlineAvailability: "Free, real-time results",
    dataAvailable: ["Entity name", "Entity number", "Formation date", "Status", "Registered agent", "Filing history"],
    steps: [
      "Go to the Ohio SOS business search portal.",
      "Enter the entity name and click Search.",
      "Click the entity in results to view details.",
      "Check Status — 'Active' is good. 'Cancelled' or 'Dissolved' indicate the entity no longer exists.",
      "Review filing history for recent amendments or agent changes.",
      "Verify statutory agent (Ohio's term for registered agent).",
    ],
    gotchas: [
      "Ohio uses the term 'Statutory Agent' instead of 'Registered Agent'.",
      "Ohio does NOT require annual reports for most entity types. This means you can't gauge activity from filing history as easily as other states.",
      "Because there are no annual reports, an Ohio LLC can exist indefinitely without any filings after formation. Check the statutory agent for signs of activity.",
    ],
    processingTime: "Real-time",
  },
  {
    slug: "illinois",
    name: "Illinois",
    abbreviation: "IL",
    sosPortalUrl: "https://www.ilsos.gov/corporatellc/CorporateLlcController",
    sosPortalName: "Illinois Secretary of State",
    entityTypes: ["LLC", "Corporation", "LP", "LLP"],
    onlineAvailability: "Free, real-time results",
    dataAvailable: ["Entity name", "File number", "Formation date", "Status", "Registered agent", "Annual reports", "Principal office"],
    steps: [
      "Go to the Illinois SOS LLC/Corporation search.",
      "Select the entity type (LLC or Corporation) from the dropdown.",
      "Enter the entity name and click Search.",
      "Click the file number to view the detail page.",
      "Check Status — 'Active/Good Standing' is the target.",
      "Review annual report filings for compliance.",
    ],
    gotchas: [
      "Illinois requires you to select LLC or Corporation before searching — if you don't know the entity type, you may need to search both.",
      "Illinois annual report fees are higher than average ($75 for LLCs, $75 for corps). Failure to file leads to involuntary dissolution.",
      "'Not in Good Standing' in Illinois usually means overdue annual reports or unpaid fees. Reinstatement is possible with back-filing.",
    ],
    processingTime: "Real-time",
  },
  {
    slug: "pennsylvania",
    name: "Pennsylvania",
    abbreviation: "PA",
    sosPortalUrl: "https://www.corporations.pa.gov/search/corpsearch",
    sosPortalName: "Pennsylvania Department of State",
    entityTypes: ["LLC", "Corporation", "LP", "LLP", "General Partnership"],
    onlineAvailability: "Free, real-time results",
    dataAvailable: ["Entity name", "Entity number", "Formation date", "Status", "Registered agent", "Filing history"],
    steps: [
      "Go to the Pennsylvania Department of State business search.",
      "Enter the entity name and click Search.",
      "Click the entity in results to view details.",
      "Check Status — 'Active' is good. 'Cancelled' or 'Dissolved' indicate issues.",
      "Review filing history for amendments and annual filings.",
      "Verify the registered office address (PA uses 'registered office' not 'registered agent' in many cases).",
    ],
    gotchas: [
      "Pennsylvania uses 'registered office' rather than 'registered agent' for many entity types.",
      "PA requires a Decennial Report (every 10 years) instead of annual reports for many entity types. This makes it harder to gauge recent activity from filings alone.",
      "The search can sometimes be slow during business hours.",
    ],
    processingTime: "Real-time",
  },
  {
    slug: "new-jersey",
    name: "New Jersey",
    abbreviation: "NJ",
    sosPortalUrl: "https://www.njportal.com/DOR/BusinessNameSearch/",
    sosPortalName: "NJ Division of Revenue",
    entityTypes: ["LLC", "Corporation", "LP", "LLP"],
    onlineAvailability: "Free, real-time results",
    dataAvailable: ["Entity name", "Entity ID", "Formation date", "Status", "Registered agent", "Annual reports"],
    steps: [
      "Go to the NJ Division of Revenue business name search.",
      "Enter the entity name and click Search.",
      "Click the entity in results to view details.",
      "Check Status — 'Active' is good standing.",
      "Review annual report filings — New Jersey requires annual reports for all entities.",
      "For more detailed filing information, you may need to use the NJBGS (Business Gateway Services) portal.",
    ],
    gotchas: [
      "New Jersey has two search systems: the basic name search (free) and the Business Gateway Services (more detailed, may require account).",
      "NJ annual reports are due on the anniversary month of formation.",
      "New Jersey revokes entities for failure to file annual reports after 2 years. Revocation requires a formal reinstatement process.",
    ],
    processingTime: "Real-time",
  },
  {
    slug: "maryland",
    name: "Maryland",
    abbreviation: "MD",
    sosPortalUrl: "https://egov.maryland.gov/BusinessExpress/EntitySearch",
    sosPortalName: "Maryland Business Express",
    entityTypes: ["LLC", "Corporation", "LP", "LLP", "Statutory Trust"],
    onlineAvailability: "Free, real-time results",
    dataAvailable: ["Entity name", "Department ID", "Formation date", "Status", "Resident agent", "Annual reports", "Principal office"],
    steps: [
      "Go to Maryland Business Express entity search.",
      "Enter the entity name and click Search.",
      "Click the entity name in results to view details.",
      "Check Status — 'Active and in Good Standing' is the target. 'Forfeited' means the entity lost its charter.",
      "Review the Annual Report / Personal Property Return filings.",
      "Verify the Resident Agent (Maryland's term for registered agent).",
    ],
    gotchas: [
      "Maryland uses the term 'Resident Agent' instead of 'Registered Agent'.",
      "Maryland combines annual reports with personal property tax returns. They're due by April 15.",
      "'Forfeited' status in Maryland means the entity's charter has been revoked. This is more severe than 'Not in Good Standing' — the entity effectively doesn't exist for legal purposes until reinstated.",
      "Maryland requires both a state filing and a local (county) business license for most businesses. The SOS only covers the state filing.",
    ],
    processingTime: "Real-time",
  },
];
